using System;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;
using AntennaAV.Models;
using System.Diagnostics;

namespace AntennaAV.Services
{
    public interface ISettingsService
    {
        AppSettings LoadSettings();
        void SaveSettings(AppSettings settings);
    }

    public class SettingsService : ISettingsService
    {
        private readonly string _settingsPath;

        public SettingsService()
        {
            var appDataPath = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
            var appFolder = Path.Combine(appDataPath, "AntennaAV");
            Directory.CreateDirectory(appFolder);
            _settingsPath = Path.Combine(appFolder, "settings.json");
        }

        public AppSettings LoadSettings()
        {
            try
            {
                if (File.Exists(_settingsPath))
                {
                    var json = File.ReadAllText(_settingsPath);
                    var settings = JsonSerializer.Deserialize(json, AppSettingsJsonSerializerContext.Default.AppSettings);
                    Debug.WriteLine($"✅ Настройки загружены из: {_settingsPath}");
                    return settings ?? new AppSettings();
                }
                else
                {
                    Debug.WriteLine($"📁 Файл настроек не найден: {_settingsPath}, используются настройки по умолчанию");
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"❌ Ошибка загрузки настроек: {ex.Message}");
            }

            return new AppSettings();
        }

        public void SaveSettings(AppSettings settings)
        {
            try
            {
                var json = JsonSerializer.Serialize(settings, AppSettingsJsonSerializerContext.Default.AppSettings);
                File.WriteAllText(_settingsPath, json);
                Debug.WriteLine($"💾 Настройки сохранены в: {_settingsPath}");
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"❌ Ошибка сохранения настроек: {ex.Message}");
            }
        }
    }

    [JsonSourceGenerationOptions(
        WriteIndented = true,
        PropertyNameCaseInsensitive = true)]
    [JsonSerializable(typeof(AppSettings))]
    internal sealed partial class AppSettingsJsonSerializerContext : JsonSerializerContext
    {
        // The partial class will have its implementation generated by the JSON source generator.
    }
}